name: Build+Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@main
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
        create_credentials_file: true
    - uses: 'aws-actions/configure-aws-credentials@v4.0.2'
      with:
        audience: sts.amazonaws.com
        role-to-assume: arn:aws:iam::716085231028:role/ComposablePromptExecutor
        role-session-name: github-actions
        aws-region: us-west-2

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm run test 
      env:
        TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        BEDROCK_REGION: us-west-2

